
@file=/media/manuel/Datos/mgallegoa/csv-node-react/data_inventory.csv

###
GET http://localhost:3000/api/users?q=manuel

###
# @file-to-variable CSV_FILE_VAR /media/manuel/Datos/mgallegoa/csv-node-react/data_inventory.csv
POST http://localhost:3000/api/files HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary{{$timestamp}}

------WebKitFormBoundary{{$timestamp}}
Content-Disposition: form-data; name="file"; filename="data_inventory.csv"
Content-Type: text/csv

{{CSV_FILE_VAR}}

------WebKitFormBoundary{{$timestamp}}
Content-Disposition: form-data; name="x"

0
------WebKitFormBoundary{{$timestamp}}
Content-Disposition: form-data; name="y"

1.4333333333333333
------WebKitFormBoundary{{$timestamp}}
Content-Disposition: form-data; name="w"

514.5666666666667
------WebKitFormBoundary{{$timestamp}}
Content-Disposition: form-data; name="h"

514.5666666666667
------WebKitFormBoundary{{$timestamp}}--
